### ISSUE TITLE
@timestamp as nanoseconds

### ISSUE THREAD

**Issue by thhet** [zenria/tracing-ecs#1]
We have an application with a mix of C# and Rust services. The C# services log the timestamps with nanosecond precision. It would be very useful if there was an option in tracing-ecs to create logs with nanosecond time stamps as well.

**Comment by zenria** [comment]
Hi, sorry for the delay... ;) 

The formatting of the timestamp is done here:

https://github.com/zenria/tracing-ecs/blob/69866539775119def29d42f044bfe191ae378d36/src/lib.rs#L264

it could use `chrono::SecondsFormat::Nanos` thus avoiding a feature flag:

```rust
Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Nanos, true)
```

WDYT?

**Comment by zenria** [comment]
Timestamp in nanos are in the 0.4.0 release of `tracing-ecs`

**Comment by thhet** [comment]
Thank you very much - works like a charm!
